// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "git.ykonkov.com/ykonkov/survey-bot/internal/entity"
	mock "github.com/stretchr/testify/mock"

	service "git.ykonkov.com/ykonkov/survey-bot/internal/service"

	uuid "github.com/google/uuid"
)

// DBRepo is an autogenerated mock type for the DBRepo type
type DBRepo struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *DBRepo) BeginTx(ctx context.Context) (service.DBTransaction, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 service.DBTransaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (service.DBTransaction, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) service.DBTransaction); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.DBTransaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSurvey provides a mock function with given fields: ctx, exec, s
func (_m *DBRepo) CreateSurvey(ctx context.Context, exec service.DBTransaction, s entity.Survey) error {
	ret := _m.Called(ctx, exec, s)

	if len(ret) == 0 {
		panic("no return value specified for CreateSurvey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, entity.Survey) error); ok {
		r0 = rf(ctx, exec, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUser provides a mock function with given fields: ctx, exec, user
func (_m *DBRepo) CreateUser(ctx context.Context, exec service.DBTransaction, user entity.User) error {
	ret := _m.Called(ctx, exec, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, entity.User) error); ok {
		r0 = rf(ctx, exec, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUserSurveyState provides a mock function with given fields: ctx, exec, state
func (_m *DBRepo) CreateUserSurveyState(ctx context.Context, exec service.DBTransaction, state entity.SurveyState) error {
	ret := _m.Called(ctx, exec, state)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSurveyState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, entity.SurveyState) error); ok {
		r0 = rf(ctx, exec, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSurvey provides a mock function with given fields: ctx, exec, surveyGUID
func (_m *DBRepo) DeleteSurvey(ctx context.Context, exec service.DBTransaction, surveyGUID uuid.UUID) error {
	ret := _m.Called(ctx, exec, surveyGUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSurvey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r0 = rf(ctx, exec, surveyGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteUserSurveyState provides a mock function with given fields: ctx, exec, userGUID, surveyGUID
func (_m *DBRepo) DeleteUserSurveyState(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID, surveyGUID uuid.UUID) error {
	ret := _m.Called(ctx, exec, userGUID, surveyGUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSurveyState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, exec, userGUID, surveyGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCompletedSurveys provides a mock function with given fields: ctx, exec, userGUID
func (_m *DBRepo) GetCompletedSurveys(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID) ([]entity.SurveyStateReport, error) {
	ret := _m.Called(ctx, exec, userGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompletedSurveys")
	}

	var r0 []entity.SurveyStateReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) ([]entity.SurveyStateReport, error)); ok {
		return rf(ctx, exec, userGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) []entity.SurveyStateReport); ok {
		r0 = rf(ctx, exec, userGUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SurveyStateReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r1 = rf(ctx, exec, userGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFinishedSurveys provides a mock function with given fields: ctx, exec, f, batchSize, offset
func (_m *DBRepo) GetFinishedSurveys(ctx context.Context, exec service.DBTransaction, f service.ResultsFilter, batchSize int, offset int) ([]entity.SurveyStateReport, error) {
	ret := _m.Called(ctx, exec, f, batchSize, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFinishedSurveys")
	}

	var r0 []entity.SurveyStateReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, service.ResultsFilter, int, int) ([]entity.SurveyStateReport, error)); ok {
		return rf(ctx, exec, f, batchSize, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, service.ResultsFilter, int, int) []entity.SurveyStateReport); ok {
		r0 = rf(ctx, exec, f, batchSize, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SurveyStateReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, service.ResultsFilter, int, int) error); ok {
		r1 = rf(ctx, exec, f, batchSize, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSurvey provides a mock function with given fields: ctx, exec, surveGUID
func (_m *DBRepo) GetSurvey(ctx context.Context, exec service.DBTransaction, surveGUID uuid.UUID) (entity.Survey, error) {
	ret := _m.Called(ctx, exec, surveGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetSurvey")
	}

	var r0 entity.Survey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) (entity.Survey, error)); ok {
		return rf(ctx, exec, surveGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) entity.Survey); ok {
		r0 = rf(ctx, exec, surveGUID)
	} else {
		r0 = ret.Get(0).(entity.Survey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r1 = rf(ctx, exec, surveGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSurveyByID provides a mock function with given fields: ctx, exec, surveyID
func (_m *DBRepo) GetSurveyByID(ctx context.Context, exec service.DBTransaction, surveyID int64) (entity.Survey, error) {
	ret := _m.Called(ctx, exec, surveyID)

	if len(ret) == 0 {
		panic("no return value specified for GetSurveyByID")
	}

	var r0 entity.Survey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int64) (entity.Survey, error)); ok {
		return rf(ctx, exec, surveyID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int64) entity.Survey); ok {
		r0 = rf(ctx, exec, surveyID)
	} else {
		r0 = ret.Get(0).(entity.Survey)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, int64) error); ok {
		r1 = rf(ctx, exec, surveyID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSurveysList provides a mock function with given fields: ctx, exec
func (_m *DBRepo) GetSurveysList(ctx context.Context, exec service.DBTransaction) ([]entity.Survey, error) {
	ret := _m.Called(ctx, exec)

	if len(ret) == 0 {
		panic("no return value specified for GetSurveysList")
	}

	var r0 []entity.Survey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction) ([]entity.Survey, error)); ok {
		return rf(ctx, exec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction) []entity.Survey); ok {
		r0 = rf(ctx, exec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Survey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction) error); ok {
		r1 = rf(ctx, exec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByGUID provides a mock function with given fields: ctx, exec, userGUID
func (_m *DBRepo) GetUserByGUID(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID) (entity.User, error) {
	ret := _m.Called(ctx, exec, userGUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByGUID")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) (entity.User, error)); ok {
		return rf(ctx, exec, userGUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) entity.User); ok {
		r0 = rf(ctx, exec, userGUID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r1 = rf(ctx, exec, userGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, exec, userID
func (_m *DBRepo) GetUserByID(ctx context.Context, exec service.DBTransaction, userID int64) (entity.User, error) {
	ret := _m.Called(ctx, exec, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int64) (entity.User, error)); ok {
		return rf(ctx, exec, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int64) entity.User); ok {
		r0 = rf(ctx, exec, userID)
	} else {
		r0 = ret.Get(0).(entity.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, int64) error); ok {
		r1 = rf(ctx, exec, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSurveyState provides a mock function with given fields: ctx, exec, userGUID, surveyGUID, states
func (_m *DBRepo) GetUserSurveyState(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID, surveyGUID uuid.UUID, states []entity.State) (entity.SurveyState, error) {
	ret := _m.Called(ctx, exec, userGUID, surveyGUID, states)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSurveyState")
	}

	var r0 entity.SurveyState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, uuid.UUID, []entity.State) (entity.SurveyState, error)); ok {
		return rf(ctx, exec, userGUID, surveyGUID, states)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, uuid.UUID, []entity.State) entity.SurveyState); ok {
		r0 = rf(ctx, exec, userGUID, surveyGUID, states)
	} else {
		r0 = ret.Get(0).(entity.SurveyState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, uuid.UUID, uuid.UUID, []entity.State) error); ok {
		r1 = rf(ctx, exec, userGUID, surveyGUID, states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSurveyStates provides a mock function with given fields: ctx, exec, userGUID, states
func (_m *DBRepo) GetUserSurveyStates(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID, states []entity.State) ([]entity.SurveyState, error) {
	ret := _m.Called(ctx, exec, userGUID, states)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSurveyStates")
	}

	var r0 []entity.SurveyState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, []entity.State) ([]entity.SurveyState, error)); ok {
		return rf(ctx, exec, userGUID, states)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, []entity.State) []entity.SurveyState); ok {
		r0 = rf(ctx, exec, userGUID, states)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.SurveyState)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, uuid.UUID, []entity.State) error); ok {
		r1 = rf(ctx, exec, userGUID, states)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersList provides a mock function with given fields: ctx, exec, limit, offset, search
func (_m *DBRepo) GetUsersList(ctx context.Context, exec service.DBTransaction, limit int, offset int, search string) (service.UserListResponse, error) {
	ret := _m.Called(ctx, exec, limit, offset, search)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersList")
	}

	var r0 service.UserListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int, int, string) (service.UserListResponse, error)); ok {
		return rf(ctx, exec, limit, offset, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, int, int, string) service.UserListResponse); ok {
		r0 = rf(ctx, exec, limit, offset, search)
	} else {
		r0 = ret.Get(0).(service.UserListResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.DBTransaction, int, int, string) error); ok {
		r1 = rf(ctx, exec, limit, offset, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetUserCurrentSurveyToNil provides a mock function with given fields: ctx, exec, userGUID
func (_m *DBRepo) SetUserCurrentSurveyToNil(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID) error {
	ret := _m.Called(ctx, exec, userGUID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserCurrentSurveyToNil")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r0 = rf(ctx, exec, userGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateActiveUserSurveyState provides a mock function with given fields: ctx, exec, state
func (_m *DBRepo) UpdateActiveUserSurveyState(ctx context.Context, exec service.DBTransaction, state entity.SurveyState) error {
	ret := _m.Called(ctx, exec, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActiveUserSurveyState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, entity.SurveyState) error); ok {
		r0 = rf(ctx, exec, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSurvey provides a mock function with given fields: ctx, exec, s
func (_m *DBRepo) UpdateSurvey(ctx context.Context, exec service.DBTransaction, s entity.Survey) error {
	ret := _m.Called(ctx, exec, s)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSurvey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, entity.Survey) error); ok {
		r0 = rf(ctx, exec, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserCurrentSurvey provides a mock function with given fields: ctx, exec, userGUID, surveyGUID
func (_m *DBRepo) UpdateUserCurrentSurvey(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID, surveyGUID uuid.UUID) error {
	ret := _m.Called(ctx, exec, userGUID, surveyGUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserCurrentSurvey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, exec, userGUID, surveyGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserLastActivity provides a mock function with given fields: ctx, exec, userGUID
func (_m *DBRepo) UpdateUserLastActivity(ctx context.Context, exec service.DBTransaction, userGUID uuid.UUID) error {
	ret := _m.Called(ctx, exec, userGUID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserLastActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.DBTransaction, uuid.UUID) error); ok {
		r0 = rf(ctx, exec, userGUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDBRepo creates a new instance of DBRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBRepo {
	mock := &DBRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
