// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "context"

	logger "git.ykonkov.com/ykonkov/survey-bot/internal/logger"
	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Errorf provides a mock function with given fields: ctx, format, args
func (_m *Logger) Errorf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Infof provides a mock function with given fields: ctx, format, args
func (_m *Logger) Infof(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// Warnf provides a mock function with given fields: ctx, format, args
func (_m *Logger) Warnf(ctx context.Context, format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, ctx, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// WithError provides a mock function with given fields: err
func (_m *Logger) WithError(err error) logger.Logger {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for WithError")
	}

	var r0 logger.Logger
	if rf, ok := ret.Get(0).(func(error) logger.Logger); ok {
		r0 = rf(err)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}

	return r0
}

// WithPrefix provides a mock function with given fields: k, v
func (_m *Logger) WithPrefix(k string, v string) logger.Logger {
	ret := _m.Called(k, v)

	if len(ret) == 0 {
		panic("no return value specified for WithPrefix")
	}

	var r0 logger.Logger
	if rf, ok := ret.Get(0).(func(string, string) logger.Logger); ok {
		r0 = rf(k, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Logger)
		}
	}

	return r0
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
