// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	entity "git.ykonkov.com/ykonkov/survey-bot/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ResultsProcessor is an autogenerated mock type for the ResultsProcessor type
type ResultsProcessor struct {
	mock.Mock
}

// GetResults provides a mock function with given fields: survey, answers
func (_m *ResultsProcessor) GetResults(survey entity.Survey, answers []entity.Answer) (entity.Results, error) {
	ret := _m.Called(survey, answers)

	if len(ret) == 0 {
		panic("no return value specified for GetResults")
	}

	var r0 entity.Results
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Survey, []entity.Answer) (entity.Results, error)); ok {
		return rf(survey, answers)
	}
	if rf, ok := ret.Get(0).(func(entity.Survey, []entity.Answer) entity.Results); ok {
		r0 = rf(survey, answers)
	} else {
		r0 = ret.Get(0).(entity.Results)
	}

	if rf, ok := ret.Get(1).(func(entity.Survey, []entity.Answer) error); ok {
		r1 = rf(survey, answers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: survey
func (_m *ResultsProcessor) Validate(survey entity.Survey) error {
	ret := _m.Called(survey)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Survey) error); ok {
		r0 = rf(survey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResultsProcessor creates a new instance of ResultsProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResultsProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResultsProcessor {
	mock := &ResultsProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
