// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	context "git.ykonkov.com/ykonkov/survey-bot/internal/context"
	entity "git.ykonkov.com/ykonkov/survey-bot/internal/entity"

	mock "github.com/stretchr/testify/mock"

	service "git.ykonkov.com/ykonkov/survey-bot/internal/service"
)

// TelegramRepo is an autogenerated mock type for the TelegramRepo type
type TelegramRepo struct {
	mock.Mock
}

// SendFile provides a mock function with given fields: ctx, path
func (_m *TelegramRepo) SendFile(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for SendFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendMessage provides a mock function with given fields: ctx, msg
func (_m *TelegramRepo) SendMessage(ctx context.Context, msg string) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSurveyList provides a mock function with given fields: ctx, states
func (_m *TelegramRepo) SendSurveyList(ctx context.Context, states []service.UserSurveyState) error {
	ret := _m.Called(ctx, states)

	if len(ret) == 0 {
		panic("no return value specified for SendSurveyList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []service.UserSurveyState) error); ok {
		r0 = rf(ctx, states)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendSurveyQuestion provides a mock function with given fields: ctx, question
func (_m *TelegramRepo) SendSurveyQuestion(ctx context.Context, question entity.Question) error {
	ret := _m.Called(ctx, question)

	if len(ret) == 0 {
		panic("no return value specified for SendSurveyQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Question) error); ok {
		r0 = rf(ctx, question)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTelegramRepo creates a new instance of TelegramRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelegramRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelegramRepo {
	mock := &TelegramRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
