{
 "title": "Technical metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Telegram API Status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(telegram_messages_total{app=\"survey-bot\"}[$__rate_interval])",
     "legendFormat": "{{func}}-{{status}}"
    }
   ]
  },
  {
   "title": "Telegram API Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, func) (rate(telegram_message_duration_seconds_bucket{app=\"survey-bot\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listener Handler Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(listener_requests_total{app=\"survey-bot\"}[$__rate_interval])",
     "legendFormat": "{{func}}-{{status}}"
    }
   ]
  },
  {
   "title": "Listener Handler Duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, func) (rate(listener_requests_duration_seconds_bucket{app=\"survey-bot\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}